### ISSUE TITLE
Question: Flashing Bootloader

### ISSUE THREAD

**Issue by kadirtunc** [pylessard/python-udsoncan#104]
Hi. Firstly, sorry for my bad English. 

I want to make my flash bootloader with this repo. But I have problem.
![WhatsApp Image 2021-12-09 at 8 02 10 PM](https://user-images.githubusercontent.com/49338130/145543018-8cbbf66f-d1b6-48a4-b6b9-745e8c976e59.jpeg)

As you know, UDS Bootloader command list like this. But I could not do this commands in my project.  

I tried this commands for unlock scurity access but it did not work.
`    client.change_session(DiagnosticSessionControl.Session.extendedDiagnosticSession)
    client.communication_control(3,3)
    client.change_session(DiagnosticSessionControl.Session.programmingSession)
    client.config['security_algo'] = myalgo

    client.unlock_security_access(1)
    req = SecurityAccess.make_request(1,SecurityAccess.Mode.RequestSeed,data=bytes())
    conn.send(req.get_payload())
    payload = conn.wait_frame(timeout =1)
    req = SecurityAccess.make_request(2,SecurityAccess.Mode.SendKey,data=bytes())
    conn.send(req.get_payload())
    payload = conn.wait_frame(timeout =1)`

Could you help me? Any example is very good for me.

**Comment by pylessard** [comment]
Hi,
First Bootloader flashing is not standardised by ISO-14229. The sequence you show in your image is specific to your ECU.

Also, many examples are available here : https://udsoncan.readthedocs.io/en/latest/udsoncan/examples.html

I suggest you use the `Client` object to make your request instead of accessing the `Connection` object directly.

When you say "it does not work", you have to give more details. Show the error you get, share a CAN log, etc.

Regards
