### ISSUE TITLE
TimeoutException and request timeout not respected?

### ISSUE THREAD

**Issue by pompushko** [pylessard/python-udsoncan#235]
@pylessard  Hello :)

I dont know, but sometimes my timeout settings wont respects...

```
                client = Client(conn, request_timeout=5)
                client.open()
                client.set_config('exception_on_negative_response', False)
                client.set_config('exception_on_timeout', False)
                client.set_config('p2_timeout', 10.0)
                client.set_config('p2_server_max', 10.0)
                client.set_config('request_timeout', 10.0)
                client.set_config('p2_star_timeout', 10.0)
                client.set_config('use_server_timing', False)
```

And sometimes my code throw this:
```[TimeoutException] : Did not receive response in time. Global request timeout time has expired (timeout=1.968 sec)```

Why? Where is takes **timeout=1.968 sec**?
Thank you.

**Comment by pylessard** [comment]
The error message is wrong. I can fix that.
You hit your 10s timeout.

What happens is that the timeout value is used to block the thread, if it unblock and there is still time to wait, a new timeout value is computed.  So 1.968 = 10-<time elapsed>. That mainly happens if your device sends a NRC 0x78, meaning it respond but ask to wait.

See here: https://github.com/pylessard/python-udsoncan/blob/master/udsoncan/client.py#L2194

**Comment by pompushko** [comment]
Hmm, so I have to extend global time to avoid long NRCs?

**Comment by pylessard** [comment]
Yes, or you can disable the global timeout by setting it to None.  Just note that the device can block your client forever if you do so

**Comment by pylessard** [comment]
Should we close this issue?

**Comment by pompushko** [comment]
> Should we close this issue?

Well, if that is not an issue or fixed, yes. Please :D

**Comment by pompushko** [comment]
> timeout=1.971 sec

well, but it think that its not 10 seconds :(

**Comment by pylessard** [comment]
![image](https://github.com/pylessard/python-udsoncan/assets/2386969/877f6fec-0abf-439f-a639-953833d3bb75)

Look at the logs
