### ISSUE TITLE
J2534Connection: [WinError 193]

### ISSUE THREAD

**Issue by MasterCodeIT** [pylessard/python-udsoncan#92]
Working with Windows 10

Trying to get the J2534 cable recv and send using your J2534Connection:

```

from udsoncan.connections import J2534Connection
conn = J2435Connection('./op20pt32.dll', rxid=0x123, txid=0x456)
```

**File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)

  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1776.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 193] %1 is not a valid Win32 application**

**Comment by mertdemirer** [comment]
May I ask how you resolved this error? I have the same problem however I am trying to connect to an ETAS hardware (es582 to be specific) and therefore they provide a different dll for j2534 connections. I am not entirely sure whether I can connect to it using a different dll but I think it should be possible since from my understanding, hardware providers should comply with the rules of j2534 while handing out these dlls.

I am using a 64 bit windows, and the dll that I am using is supposedly supported on 64 bit windows however I have suspicions that it actually runs on 32 bit since the dll was installed to C:\Program Files (x86). Perhaps this was the issue you faced and you fixed it with finding the 64 bit version of the dll?
